import React from 'react'
import Head from 'next/head'

function comingsoon() {
  return (
    <>
     <Head>
        <title>Coming soon...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/site logo.png" />
      </Head>
      <h1> Coming soon</h1>
    </>
  )
}

export default comingsoon
