import React from 'react'
import Head from 'next/head'

function index() {
  return (
    <>
       <Head>
        <title>Download free tv-series, sign up here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/site logo.png" />
      </Head>
      <h1>Sign up </h1>
    </>
  )
}

export default index
