import React from 'react'
import Head from 'next/head'

function news() {
  return (
    <div>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/site logo.png" />
      </Head>
      <h1>News</h1>
    </div>
  )
}

export default news
