import React from 'react'
import Head from 'next/head'

function tvseries() {
  return (
    <>
      <Head>
        <title>Tv series</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/site logo.png" />
      </Head>
      <h1> Tv series</h1>
    </>
  )
}

export default tvseries
